version: "3.9"
services:
  node:
    build:
      context: ./docker/node
    volumes:
      - ./:/usr/app
    stdin_open: true 
    tty: true
    ports:
      - ${SERVER_PORT:-3000}:3000
      - 24678:24678